### PR TITLE
Update: start server to use ipv4 by default

### PR DESCRIPTION
**Pull request by molee1905**

### CODE REVIEW

**Comment by 2betop** [comment]
Why?

**Comment by molee1905** [comment]
when check the page on the mobile, it's more convenient using ipv4 (e.g. http://192.168.1.1) than just 127.0.0.1

**Comment by 2betop** [comment]
But this can not help, it can not open the browser in your mobile.

**Comment by molee1905** [comment]
it is really useful when debug page on mobile via the corporate intranet. think about that, you run fis on pc，opened http://127.0.0.1:8080/index.html,  how to see it on mobile? 
```bash
$ ifconfig |grep inet
```
pick up the ipv4: 192.168.1.100; then open http://192.168.1.100:8080/index.html by using the broswer of your mobile, okey, finally, you see the result and can check the different between pc and mobile...

Uh，as you see, your coffee may be cold after such a long process. it's time to make change

**Comment by 2betop** [comment]
```bash
fis3 server start                              [18:48:47]

 [INFO] Currently running fis3 (omit...)

 Starting fis-server .. at port [8080]

 [INFO] Browse http://127.0.0.1:8080/

 [INFO] Or browse  http://192.168.1.100:8080/
```

Your don't need to run  `ifconfig` at all, noticed the information `http://192.168.1.100:8080/`?

It has to be the url ` http://192.168.1.100:8080/` for mobile, I admit it. But for pc, it does not.

So I said it can not help at all.

**Comment by 2betop** [comment]
And I do believe this can help.

image

**Comment by molee1905** [comment]
yeah, i see, but typing http://192.168.1.100:8080/index.html on your mobile broswer word by word or using QR code, which one do you like? i mean, when open  http://192.168.1.100:8080 by default, you can generate QR code directly using some chrome plugin, and then use your mobile browse scan the code, save a lot of your time

**Comment by molee1905** [comment]
yeah, generating QR code directly is what i need

**Comment by molee1905** [comment]
fis3 can generat3 QR code on command line ? i'm now using fis2

**Comment by 2betop** [comment]
I will add this feature, soon.

**Comment by molee1905** [comment]
good!   dose it support fis2 ? i can not switch to fis3 in a short time

**Comment by 2betop** [comment]
Ok, fis2 will support too.

**Comment by molee1905** [comment]
Awesome !  [qr code](https://github.com/fex-team/fis-command-server/commit/83d342524691bbc8637e886d286a4aa48bf35b3c) is now available from command line when start fis server. But there is still one stutation, for example, if a url is not ending with 'index.html' but 'xxx/yy/test.html', (http://192.168.1.100:8080/xxx/yy/test.html) , the qrcode in command line seems powerless. I still perfer open ip not 127.0.0.1 by default, or would you give some insights why not use ip by default?

**Pull request closed without merging**
